/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.spendituretracker.view;

import com.java.spendituretracker.view.category.CategoryView;
import com.java.spendituretracker.view.income.IncomeView;
import com.java.spendituretracker.view.summary.SummaryView;

/**
 *
 * @author Calcey
 */
public class MainView extends javax.swing.JFrame {

    private SummaryView summaryView;
        private CategoryView categoryView;
        private IncomeView incomeView;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        LoadSummaryView(1);
        LoadCategoryView();
        LoadIncomeView(1);
    }
    
    private  void LoadSummaryView(int month){
        
        summaryView = new SummaryView(month);
        summaryView.setBounds(0,0,mainContainer.getWidth(), mainContainer.getHeight());
        this.mainContainer.add(summaryView);
    }
    private  void LoadCategoryView(){
        
        categoryView = new CategoryView();
        categoryView.setBounds(0,0,CategoryContainer.getWidth(), CategoryContainer.getHeight());
        this.CategoryContainer.add(categoryView);
    }
    private  void LoadIncomeView(int month){
        
        incomeView = new IncomeView(month);
        incomeView.setBounds(0,0,jPanelIncomeContainer.getWidth(), jPanelIncomeContainer.getHeight());
        this.jPanelIncomeContainer.add(incomeView);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        monthNameCmb = new javax.swing.JComboBox<String>();
        mainSummaryScorllPanel = new javax.swing.JScrollPane();
        mainContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        incomeContainer = new javax.swing.JPanel();
        incomeMonthNameCmb = new javax.swing.JComboBox<String>();
        jPanelIncomeContainer = new javax.swing.JPanel();
        CategoryContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        monthNameCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthNameCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthNameCmbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        mainSummaryScorllPanel.setViewportView(mainContainer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(monthNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(mainSummaryScorllPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monthNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainSummaryScorllPanel))
        );

        jTabbedPane5.addTab("Summary", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Expenditure", jPanel2);

        incomeMonthNameCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        incomeMonthNameCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                incomeMonthNameCmbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelIncomeContainerLayout = new javax.swing.GroupLayout(jPanelIncomeContainer);
        jPanelIncomeContainer.setLayout(jPanelIncomeContainerLayout);
        jPanelIncomeContainerLayout.setHorizontalGroup(
            jPanelIncomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        jPanelIncomeContainerLayout.setVerticalGroup(
            jPanelIncomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout incomeContainerLayout = new javax.swing.GroupLayout(incomeContainer);
        incomeContainer.setLayout(incomeContainerLayout);
        incomeContainerLayout.setHorizontalGroup(
            incomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeContainerLayout.createSequentialGroup()
                .addGroup(incomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(incomeContainerLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(incomeMonthNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(incomeContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelIncomeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        incomeContainerLayout.setVerticalGroup(
            incomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incomeMonthNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelIncomeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Income", incomeContainer);

        javax.swing.GroupLayout CategoryContainerLayout = new javax.swing.GroupLayout(CategoryContainer);
        CategoryContainer.setLayout(CategoryContainerLayout);
        CategoryContainerLayout.setHorizontalGroup(
            CategoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        CategoryContainerLayout.setVerticalGroup(
            CategoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Category", CategoryContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthNameCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthNameCmbItemStateChanged
        if(summaryView != null){
            this.mainContainer.remove(summaryView);
            this.mainContainer.revalidate();
            this.mainContainer.repaint();                    
        }        
        LoadSummaryView(monthNameCmb.getSelectedIndex()+1);
    }//GEN-LAST:event_monthNameCmbItemStateChanged

    private void incomeMonthNameCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_incomeMonthNameCmbItemStateChanged
  if(incomeView != null){
            this.jPanelIncomeContainer.remove(incomeView);
            this.jPanelIncomeContainer.revalidate();
            this.jPanelIncomeContainer.repaint();                    
        }        
        LoadIncomeView(incomeMonthNameCmb.getSelectedIndex()+1);    }//GEN-LAST:event_incomeMonthNameCmbItemStateChanged

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CategoryContainer;
    private javax.swing.JPanel incomeContainer;
    private javax.swing.JComboBox<String> incomeMonthNameCmb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelIncomeContainer;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JScrollPane mainSummaryScorllPanel;
    private javax.swing.JComboBox<String> monthNameCmb;
    // End of variables declaration//GEN-END:variables
}
